export const ROUTES = {
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  DASHBOARD: "/",
  TENANTS: "/tenants",
  TENANT_CONNECT: "/tenants/connect",
  TENANT_DETAIL: (id: string) => `/tenants/${id}`,
  MIGRATIONS: "/migrations",
  MIGRATION_NEW: "/migrations/new",
  MIGRATION_DETAIL: (id: string) => `/migrations/${id}`,
  MIGRATION_MAPPINGS: (id: string) => `/migrations/${id}/mappings`,
  MIGRATION_ERRORS: (id: string) => `/migrations/${id}/errors`,
  MIGRATION_DEAD_LETTER: (id: string) => `/migrations/${id}/dead-letter`,
  MIGRATION_REPORT: (id: string) => `/migrations/${id}/report`,
  TEAM: "/team",
  BILLING: "/billing",
  ACTIVITY: "/activity",
  SETTINGS: "/settings",
  SETTINGS_API_KEYS: "/settings/api-keys",
  SETTINGS_WEBHOOKS: "/settings/webhooks",
} as const;

export const QUERY_KEYS = {
  AUTH_ME: ["auth", "me"],
  DASHBOARD_STATS: ["dashboard", "stats"],
  DASHBOARD_ACTIVITY: ["dashboard", "activity"],
  TENANTS: ["tenants"],
  TENANT: (id: string) => ["tenants", id],
  DISCOVERY: (tenantId: string) => ["discovery", tenantId],
  MIGRATIONS: ["migrations"],
  MIGRATION: (id: string) => ["migrations", id],
  MIGRATION_TASKS: (id: string) => ["migrations", id, "tasks"],
  MIGRATION_ERRORS: (id: string) => ["migrations", id, "errors"],
  MIGRATION_REPORT: (id: string) => ["migrations", id, "report"],
  MIGRATION_DEAD_LETTER: (id: string) => ["migrations", id, "dead-letter"],
  MAPPINGS: (jobId: string) => ["mappings", jobId],
  MAPPING_SUMMARY: (jobId: string) => ["mappings", jobId, "summary"],
  MAPPING_VALIDATE: (jobId: string) => ["mappings", jobId, "validate"],
  USERS: ["users"],
  INVITATIONS: ["users", "invitations"],
  SUBSCRIPTION: ["billing", "subscription"],
  USAGE: ["billing", "usage"],
  INVOICES: ["billing", "invoices"],
  WEBHOOKS: ["webhooks"],
  ACTIVITY_LOGS: ["activity-logs"],
  ORGANIZATION: ["organization"],
} as const;

export const STATUS_COLORS: Record<string, { bg: string; text: string; dot: string }> = {
  CREATED: { bg: "bg-muted", text: "text-muted-foreground", dot: "bg-muted-foreground" },
  DISCOVERY: { bg: "bg-info/10", text: "text-info", dot: "bg-info" },
  MAPPING: { bg: "bg-brand-50", text: "text-brand-700", dot: "bg-brand-500" },
  PRE_MIGRATION: { bg: "bg-warning/10", text: "text-warning", dot: "bg-warning" },
  MIGRATION: { bg: "bg-brand-100", text: "text-brand-700", dot: "bg-brand-600" },
  VALIDATION: { bg: "bg-info/10", text: "text-info", dot: "bg-info" },
  CUTOVER: { bg: "bg-warning/10", text: "text-warning", dot: "bg-warning" },
  COMPLETED: { bg: "bg-success/10", text: "text-success", dot: "bg-success" },
  FAILED: { bg: "bg-destructive/10", text: "text-destructive", dot: "bg-destructive" },
  PAUSED: { bg: "bg-muted", text: "text-muted-foreground", dot: "bg-muted-foreground" },
  CANCELLED: { bg: "bg-muted", text: "text-muted-foreground", dot: "bg-muted-foreground" },
  CONNECTED: { bg: "bg-success/10", text: "text-success", dot: "bg-success" },
  DISCONNECTED: { bg: "bg-muted", text: "text-muted-foreground", dot: "bg-muted-foreground" },
  ERROR: { bg: "bg-destructive/10", text: "text-destructive", dot: "bg-destructive" },
  PENDING: { bg: "bg-warning/10", text: "text-warning", dot: "bg-warning" },
  MATCHED: { bg: "bg-success/10", text: "text-success", dot: "bg-success" },
  UNMATCHED: { bg: "bg-warning/10", text: "text-warning", dot: "bg-warning" },
  SKIPPED: { bg: "bg-muted", text: "text-muted-foreground", dot: "bg-muted-foreground" },
  ACTIVE: { bg: "bg-success/10", text: "text-success", dot: "bg-success" },
  INACTIVE: { bg: "bg-muted", text: "text-muted-foreground", dot: "bg-muted-foreground" },
};

export const MIGRATION_PHASES = [
  "CREATED",
  "DISCOVERY",
  "MAPPING",
  "PRE_MIGRATION",
  "MIGRATION",
  "VALIDATION",
  "CUTOVER",
  "COMPLETED",
] as const;

export const PHASE_LABELS: Record<string, string> = {
  CREATED: "Created",
  DISCOVERY: "Discovery",
  MAPPING: "Mapping",
  PRE_MIGRATION: "Pre-Migration",
  MIGRATION: "Migration",
  VALIDATION: "Validation",
  CUTOVER: "Cutover",
  COMPLETED: "Completed",
};
